### ISSUE TITLE
目前复刻到什么程度了？what is the roadmap this project

### ISSUE THREAD

**Issue by cuihee** [aseaday/MarkovJunior.js#6]
are those models code work in MarkovJunior.js Demo ? 
https://github.com/mxgmn/MarkovJunior/tree/main/models

what is the different between [MarkovJunior.js](https://github.com/aseaday/MarkovJunior.js) and [MarkovJunior](https://github.com/mxgmn/MarkovJunior), in functional not language

----
原版库提供的模型代码可以用么？（为什么我在demo中跑不出来预期的效果）

目前和原版有哪些功能上的差异？

**Comment by cuihee** [comment]
i missed 
Plan.md

that is the info i need

---
刚没看见
Plan.md
文件

**Comment by lalawuu** [comment]
不好意思，上周比较忙，这周会把基本的节点支持更新完。
